name: Build and Deploy to Linode
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.109
      - name: Install Dependencies
        run: dotnet restore
      - name: Build App
        run: dotnet publish -c Release --no-restore
      - name: Move Environment Files
        run: mv ./scripts/environment/*  ./src/RawCoding.Shop.UI/bin/Release/netcoreapp3.1/publish/
      - name: Inject Secrets
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/RawCoding.Shop.UI/bin/Release/netcoreapp3.1/publish/appsettings.Production.json'
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.POSTGRESQL_CONNECTION_STRING }}
          StripeSettings.PublicKey: ${{ secrets.STRIPE_PUBLIC }}
          StripeSettings.SecretKey: ${{ secrets.STRIPE_SECRET }}
          EmailSettings.Account: ${{ secrets.GMAIL_SMTP_ACCOUNT }}
          EmailSettings.Password: ${{ secrets.GMAIL_SMTP_PASSWORD }}
          S3StorageSettings.AccessKey: ${{ secrets.LINODE_S3_ACCESS }}
          S3StorageSettings.SecretKey: ${{ secrets.LINODE_S3_SECRET }}
          AdminPassword: ${{ secrets.SHOP_ADMIN_PASSWORD }}
      - name: Push To Linode
        run: |
          echo "$ssh_key" > ~/ssh_key
          chmod 600 ~/ssh_key
          rsync -e "ssh -i ~/ssh_key -o StrictHostKeyChecking=no" -avrz ./src/RawCoding.Shop.UI/bin/Release/netcoreapp3.1/publish/* github_actions@"$target_ip":/var/app/shop
        env:
          ssh_key: ${{ secrets.LINODE_SSH }}
          target_ip: ${{ secrets.LINODE_VM_IP }}
